export enum EventTags {
  FreeEntry = "Free Entry",
  OnlineEvent = "Online Event",
  InPerson = "In-Person",
  Coding = "Coding",
  Gaming = "Gaming",
  Music = "Music",
  Art = "Art",
  Food = "Food",
  Fashion = "Fashion",
  Sports = "Sports",
  Technology = "Technology",
  Science = "Science",
  Health = "Health",
  Wellness = "Wellness",
  Travel = "Travel",
  Education = "Education",
  Business = "Business",
  Entertainment = "Entertainment",
  CareerGrowth = "Career Growth",
  Other = "Other",
}
